apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
   - ReadWriteMany
  #storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  