apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec: # Cronjob SPec
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: # Job Spec
      template:
        spec: #Pod Spec
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure