apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec: # Cronjob SPec
  startingDeadlineSeconds: 17 #Terminated if it takes more than 17 seconds to start execution after its schedule
  schedule: "*/1 * * * *" # Every one minute
  jobTemplate:
    spec: # Job Spec
      template:
        spec: #Pod Spec
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure