apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 10 # specify the number of retries before considering a Job as failed
  parallelism: 3 # Specify the parallel pods creation
  completions: 3 # No of total pod creation before complete