apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liveness-deploy
  name: liveness-http
spec:
  selector:
    matchLabels:
      app: liveness
      tier: web
  template:
    metadata:
     labels:
       app: liveness
       tier: web
     name: liveness-pod
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/liveness
        args:
        - /server
        livenessProbe:
         httpGet:
          path: /healthz
          port: 8080
          httpHeaders:
          - name: Custom-Header
            value: Awesome
         initialDelaySeconds: 3
         periodSeconds: 3
         timeoutSeconds: 3


