apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
spec:
  capacity:
    storage: 400Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  gcePersistentDisk:
    ## This GCE PD must already exist.   # gcloud compute disks create --size=500GB --zone=us-central1-a my-data-disk
    pdName: my-data-disk
    fsType: ext4
  # awsElasticBlockStore:
    # pdName: aws-ebs-disk-name
    # volume_id
    # fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-a
          - us-central1-b