apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: fast # Refer to storageClassName under spec in persistent-volume.yaml
  resources:
    requests:
      storage: 300Gi # Refer to storage under spec:capacity in persistent-volume.yaml
  