apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: gcpstorage # Refer to metadata.name in storageclass-gcp.yaml
  resources:
    requests:
      storage: 300Gi
  