apiVersion: v1
kind: Pod
metadata:
  name: dooku
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - mountPath: /var/log/dooku
      name: dooku-logs
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/dooku
      name: dooku-logs
  volumes:
  - name: dooku-logs
    hostPath:
      path: /data/dooku
