apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-10-10T04:26:00Z"
  name: elephant
  namespace: default
  resourceVersion: "3066"
  selfLink: /api/v1/namespaces/default/pods/elephant
  uid: 5b9bf95f-1386-46ea-aec9-fb230ab4c048
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jn2kb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jn2kb
    secret:
      defaultMode: 420
      secretName: default-token-jn2kb
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-10-10T04:26:00Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-10-10T04:26:00Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-10-10T04:26:00Z"
    message: 'containers with unready status: [mem-stress]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-10-10T04:26:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0b8223a66a5ee9f823025b4e12b975b90aaef1d53195d6b537b302ab68ac5738
    image: polinux/stress:latest
    imageID: docker-pullable://polinux/stress@sha256:b6144f84f9c15dac80deb48d3a646b55c7043ab1d83ea0a697c09097aaad21aa
    lastState:
      terminated:
        containerID: docker://0b8223a66a5ee9f823025b4e12b975b90aaef1d53195d6b537b302ab68ac5738
        exitCode: 1
        finishedAt: "2020-10-10T04:27:41Z"
        reason: OOMKilled
        startedAt: "2020-10-10T04:27:41Z"
    name: mem-stress
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=mem-stress pod=elephant_default(5b9bf95f-1386-46ea-aec9-fb230ab4c048)
        reason: CrashLoopBackOff
  hostIP: 172.17.0.27
  phase: Running
  podIP: 10.244.1.3
  podIPs:
  - ip: 10.244.1.3
  qosClass: Burstable
  startTime: "2020-10-10T04:26:00Z"