apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness-goproxy-deploy
  name: readiness-goproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goproxy
  template:
    metadata:
     name: goproxy
     labels:
      app: goproxy
    spec:
     containers:
     - name: goproxy
       image: k8s.gcr.io/goproxy:0.1
       ports:
       - containerPort: 8080
       readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
       livenessProbe:
         tcpSocket:
          port: 8080
         initialDelaySeconds: 15
         periodSeconds: 20