apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
  labels:
    app: employee-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-pod
      tier: web
  template:
   metadata:
      labels:
        app: employee-pod
        tier: web
   spec:
     containers:
     - name: kubernetes-secret
       image: eshghos/kubernetes-secret:latest
       ports:
        - containerPort: 8081
       volumeMounts:
       - name: foo
         mountPath: "/etc/foo"
       - name: mysecretvolume
         mountPath: "/etc/secret"
     volumes:
     - name: foo
       secret:
        secretName: mysql-secret # kubectl exec -it mysecretpod cat /etc/foo/ # Refers metadata.name in secret.yaml
        defaultMode: 0400
     - name: mysecretvolume # username secret is stored under /etc/foo/my-group/my-username file instead of /etc/secret/username
       secret:
        secretName: mysql-secret
        defaultMode: 0400
        items:
        - key: username
          path: my-group/my-username # kubectl exec -it mysecretpod cat /etc/secret/my-group/my-username
        - key: password 
          path: my-group/my-password # kubectl exec -it mysecretpod cat /etc/secret/my-group/my-password