apiVersion: v1
kind: Service
metadata:
  name: mysql # DNS name 
  labels:
    app: onehrservice
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: onehr
    tier: mysql
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  