apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-claim
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: fast # Refer to storageClassName under spec in persistent-volume.yaml
  resources:
    requests:
      storage: 80Mi # Refer to storage under spec:capacity in persistent-volume.yaml
  