apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  gcePersistentDisk:
    ## This GCE PD must already exist.   # gcloud compute disks create --size=500GB --zone=us-central1-a my-data-disk
    pdName: mastervm
    fsType: ext4