apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-storage
spec:
  storageClassName: "slow" 
  resources:
    requests:
      storage: 1Gi
  accessModes:
   - ReadWriteMany